#====================================
#              Plugins
#====================================

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll_dynamic_assets
  - jekyll-terser

#====================================
#             Variables
#====================================

url: "https://mumarshahbaz.github.io"
baseurl: "/Oscilloscope-3"
title: Oscilloscope Online
description: Oscilloscope Online is a versatile web-based graphing tool designed to make data visualization quick and intuitive. It supports multiple input formats and provides an easy, streamlined way to convert raw data into clear, informative graphs.
lang: "en"
keywords: [oscilloscope, online, web serial, plotter, electronics, data visualization, signal analysis, customisation, open source]
author: M. Umar Shahbaz

#====================================
#      Collections (Sub Sections)
#====================================

collections:
  audio:
    output: true
    name: Audio Visualizer
  code:
    output: true
    name: Code
  forms:
    output: true
    name: Google Forms
  maths:
    output: true
    name: Maths
  serial:
    output: true
    name: Serial Plotter
  table:
    output: true
    name: Table

#====================================
#            Head Assets
#====================================

dynamic_assets:
  absolute: true
  source:
    base: /assets
    css: /css
  formats:
    defer-js: <script defer src="%s"></script>
    preload-css: <link rel="preload" href="%s" as="style" onload="this.onload=null;this.rel='stylesheet'">
    noscript-css: <noscript><link rel="stylesheet" href="%s"></noscript>
    preload-img: <link rel="preload" as="image" href="%s">
    preload-woff2: <link rel="preload" href="%s" as="font" type="font/woff2" crossorigin>
  master:
   - tailwind.css::preload-css
   - tailwind.css::noscript-css
   - master.css::preload-css
   - master.css::noscript-css

#====================================
#         Asset Optimization
#====================================

sass:
  style: compressed
  sourcemap: never
  quiet_deps: false

jekyll-minifier:
  compress_javascript: false

terser:
  compress:
    drop_console: true

#====================================
#              Excludes
#====================================

exclude:
  - .bundle/
  - .vscode/
  - node_modules/
  - scripts/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - package.json
  - package-lock.json
  - README.md