#====================================
#              Plugins
#====================================

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll_dynamic_assets
  - jekyll-terser

#====================================
#             Variables
#====================================

url: "https://mumarshahbaz.github.io"
baseurl: "/Oscilloscope-3"
title: Oscilloscope Online
description: Oscilloscope Online is a versatile web-based graphing tool designed to make data visualization quick and intuitive. It supports multiple input formats and provides an easy, streamlined way to convert raw data into clear, informative graphs.
lang: "en"
keywords: [oscilloscope, online, web serial, plotter, electronics, data visualization, signal analysis, customisation, open source]
author: M. Umar Shahbaz

#====================================
#      Collections (Sub Sections)
#====================================

collections:
  serial:
    output: true
  hot:
    output: true
  code:
    output: true
  forms:
    output: true
  audio:
    output: true
  maths:
    output: true

#====================================
#         Asset Optimization
#====================================

sass:
  style: compressed
  sourcemap: never
  quiet_deps: false

jekyll-minifier:
  compress_javascript: false

terser:
  compress:
    drop_console: true

#====================================
#              Excludes
#====================================

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md